insert into dependency_movie (id,title,"elementID") values (1795, 'Prometheus','prometheus');
insert into dependency_movie (id,title,"elementID") values (1806, 'The Martian','martian');
insert into dependency_movie (id,title,"elementID") values (1807, 'Aliens','aliens');
insert into dependency_movie (id,title,"elementID") values (1808, '2001: A Space Odyssey','2001-space-odyssey');
insert into dependency_movie (id,title,"elementID") values (1809, '2010: The Year We Make Contact','2010-year-we-make-contact');
insert into dependency_movie (id,title,"elementID") values (1810, '400 days','400-days');
insert into dependency_movie (id,title,"elementID") values (1811, 'Abbott and Costello Go To Mars','abbott-and-costello-go-mars');
insert into dependency_movie (id,title,"elementID") values (1812, 'Abyss, The','abyss');
insert into dependency_movie (id,title,"elementID") values (1813, 'Adventures of Buckaroo Banzai, The','adventures-buckaroo-banzai');
insert into dependency_movie (id,title,"elementID") values (1814, 'Adventures of Pluto Nash, The','adventures-pluto-nash');
insert into dependency_movie (id,title,"elementID") values (1815, 'After Earth','after-earth');
insert into dependency_movie (id,title,"elementID") values (1816, 'Airplane II: The Sequel','airplane-ii-sequel');
insert into dependency_movie (id,title,"elementID") values (1817, 'Alien','alien');
insert into dependency_movie (id,title,"elementID") values (1818, 'Alien Planet','alien-planet');
insert into dependency_movie (id,title,"elementID") values (1819, 'Alien 3','alien-3');
insert into dependency_movie (id,title,"elementID") values (1820, 'Alien Outpost','alien-outpost');
insert into dependency_movie (id,title,"elementID") values (1821, 'Alien Resurrection','alien-resurrection');
insert into dependency_movie (id,title,"elementID") values (1822, 'AVP: Alien vs. Predator','avp-alien-vs-predator');
insert into dependency_movie (id,title,"elementID") values (1823, 'Aliens vs. Predator: Requiem','aliens-vs-predator-requiem');
insert into dependency_movie (id,title,"elementID") values (1824, 'American Astronaut, The','american-astronaut');
insert into dependency_movie (id,title,"elementID") values (1825, 'Android','android');
insert into dependency_movie (id,title,"elementID") values (1826, 'Andromeda Strain, The','andromeda-strain');
insert into dependency_movie (id,title,"elementID") values (1827, 'Apollo 13','apollo-13');
insert into dependency_movie (id,title,"elementID") values (1828, 'Apollo 18','apollo-18');
insert into dependency_movie (id,title,"elementID") values (1829, 'Armageddon','armageddon');
insert into dependency_movie (id,title,"elementID") values (1830, 'Angry Red Planet, The','angry-red-planet');
insert into dependency_movie (id,title,"elementID") values (1831, 'Arrival, The','the_arrival');
insert into dependency_movie (id,title,"elementID") values (1832, 'Astronaut Farmer, The','astronaut-farmer');
insert into dependency_movie (id,title,"elementID") values (1833, 'Astronaut Wives Club, The','astronaut-wives-club');
insert into dependency_movie (id,title,"elementID") values (1834, 'Astronaut''s Wife, The','astronauts-wife');
insert into dependency_movie (id,title,"elementID") values (1835, 'Avatar','avatar');
insert into dependency_movie (id,title,"elementID") values (1836, 'Barbarella','barbarella');
insert into dependency_movie (id,title,"elementID") values (1837, 'Battle Beyond the Stars','battle-beyond-stars');
insert into dependency_movie (id,title,"elementID") values (1838, 'Battlefield Earth','battlefield-earth');
insert into dependency_movie (id,title,"elementID") values (1839, 'Battlespace','battlespace');
insert into dependency_movie (id,title,"elementID") values (1840, 'Black Hole, The','black-hole');
insert into dependency_movie (id,title,"elementID") values (1842, 'Blade Runner','blade-runner');
insert into dependency_movie (id,title,"elementID") values (1843, 'Capricorn One','capricorn-one');
insert into dependency_movie (id,title,"elementID") values (1844, 'Cargo','cargo');
insert into dependency_movie (id,title,"elementID") values (1845, 'Cat-Women of the Moon','cat-women-moon');
insert into dependency_movie (id,title,"elementID") values (1846, 'Chronicles of Riddick','chronicles-riddick');
insert into dependency_movie (id,title,"elementID") values (1847, 'Close Encounters of the Third Kind','close-encounters-third-kind');
insert into dependency_movie (id,title,"elementID") values (1848, 'Conquest of Space','conquest-space');
insert into dependency_movie (id,title,"elementID") values (1849, 'Contact','contact');
insert into dependency_movie (id,title,"elementID") values (1850, 'Core, The','core');
insert into dependency_movie (id,title,"elementID") values (1851, 'Countdown','countdown');
insert into dependency_movie (id,title,"elementID") values (1852, 'Critters 4','critters-4');
insert into dependency_movie (id,title,"elementID") values (1853, 'Dante 01','dante-01');
insert into dependency_movie (id,title,"elementID") values (1854, 'Dark Star','dark-star');
insert into dependency_movie (id,title,"elementID") values (1855, 'Day the Earth Stood Still, The','day-earth-stood-still');
insert into dependency_movie (id,title,"elementID") values (1856, 'Day the Earth Stood Still, The','day-earth-stood-still-0');
insert into dependency_movie (id,title,"elementID") values (1857, 'Deep Impact','deep-impact');
insert into dependency_movie (id,title,"elementID") values (1858, 'Destination Moon','destination-moon');
insert into dependency_movie (id,title,"elementID") values (1859, 'District 9','district-9');
insert into dependency_movie (id,title,"elementID") values (1860, 'Doom','doom');
insert into dependency_movie (id,title,"elementID") values (1861, 'Dracula 3000','dracula-3000');
insert into dependency_movie (id,title,"elementID") values (1862, 'Drift, The','drift');
insert into dependency_movie (id,title,"elementID") values (1863, 'Dune','dune');
insert into dependency_movie (id,title,"elementID") values (1864, 'Elysium','elysium');
insert into dependency_movie (id,title,"elementID") values (1865, 'Ender''s Game','enders-game');
insert into dependency_movie (id,title,"elementID") values (1866, 'Enemy Mine','enemy-mine');
insert into dependency_movie (id,title,"elementID") values (1867, 'E.T. the Extra-Terrestrial','et-extra-terrestrial');
insert into dependency_movie (id,title,"elementID") values (1868, 'Europa Report','europa-report');
insert into dependency_movie (id,title,"elementID") values (1869, 'Event Horizon','event-horizon');
insert into dependency_movie (id,title,"elementID") values (1870, 'Explorers','explorers');
insert into dependency_movie (id,title,"elementID") values (1871, 'Fantastic Planet','fantastic-planet');
insert into dependency_movie (id,title,"elementID") values (1872, 'Fifth Element, The','fifth-element');
insert into dependency_movie (id,title,"elementID") values (1873, 'Final Fantasy: The Spirits Within','final-fantasy-spirits-within');
insert into dependency_movie (id,title,"elementID") values (1874, 'First Man Into Space','first-man-space');
insert into dependency_movie (id,title,"elementID") values (1875, 'First Men in the Moon','first-men-moon');
insert into dependency_movie (id,title,"elementID") values (1876, 'First Spaceship on Venus','first-spaceship-venus');
insert into dependency_movie (id,title,"elementID") values (1877, 'Flash Gordon','flash-gordon');
insert into dependency_movie (id,title,"elementID") values (1878, 'Flight to Mars','flight-mars');
insert into dependency_movie (id,title,"elementID") values (1879, 'Forbidden Planet','forbidden-planet');
insert into dependency_movie (id,title,"elementID") values (1880, 'Fortress 2','fortress-2');
insert into dependency_movie (id,title,"elementID") values (1881, 'Halo 4: Forward Unto Dawn','halo-4-forward-unto-dawn');
insert into dependency_movie (id,title,"elementID") values (1882, 'Halo: Nightfall','halo-nightfall');
insert into dependency_movie (id,title,"elementID") values (1883, 'Fountain, The','fountain');
insert into dependency_movie (id,title,"elementID") values (1884, 'From the Earth to the Moon','earth-moon');
insert into dependency_movie (id,title,"elementID") values (1885, 'Galaxina','galaxina');
insert into dependency_movie (id,title,"elementID") values (1886, 'Galaxy Quest','galaxy-quest');
insert into dependency_movie (id,title,"elementID") values (1887, 'Galaxy of Terror','galaxy-terror');
insert into dependency_movie (id,title,"elementID") values (1888, 'Gattaca','gattaca');
insert into dependency_movie (id,title,"elementID") values (1889, 'Ghosts of Mars','ghosts-mars');
insert into dependency_movie (id,title,"elementID") values (1890, 'G.O.R.A.','gora');
insert into dependency_movie (id,title,"elementID") values (1891, 'Guardians of the Galaxy','guardians-galaxy');
insert into dependency_movie (id,title,"elementID") values (1892, 'Gravity','gravity');
insert into dependency_movie (id,title,"elementID") values (1893, 'Hellraiser: Bloodline','hellraiser-bloodline');
insert into dependency_movie (id,title,"elementID") values (1894, 'High Moon','high-moon');
insert into dependency_movie (id,title,"elementID") values (1895, 'Hitchhiker''s Guide to the Galaxy, The','hitchhikers-guide-galaxy');
insert into dependency_movie (id,title,"elementID") values (1896, 'Humanity''s End','humanitys-end');
insert into dependency_movie (id,title,"elementID") values (1897, 'Hunter Prey','hunter-prey');
insert into dependency_movie (id,title,"elementID") values (1898, 'Ice Pirates, The','ice-pirates');
insert into dependency_movie (id,title,"elementID") values (1899, 'Independence Day','independence-day');
insert into dependency_movie (id,title,"elementID") values (1900, 'Infini','infini');
insert into dependency_movie (id,title,"elementID") values (1901, 'Interstellar','interstellar');
insert into dependency_movie (id,title,"elementID") values (1902, 'Iron Sky','iron-sky');
insert into dependency_movie (id,title,"elementID") values (1903, 'It!  The Terror from Beyond Space','it-terror-beyond-space');
insert into dependency_movie (id,title,"elementID") values (1904, 'Jason X','jason-x');
insert into dependency_movie (id,title,"elementID") values (1905, 'John Carter','john-carter');
insert into dependency_movie (id,title,"elementID") values (1906, 'Journey to the 7th Planet','journey-7th-planet');
insert into dependency_movie (id,title,"elementID") values (1907, 'Journey to the Far Side of the Sun','journey-far-side-sun');
insert into dependency_movie (id,title,"elementID") values (1908, 'Jupiter Ascending','jupiter-ascending');
insert into dependency_movie (id,title,"elementID") values (1909, 'Killings at Outpost Zeta, The','killings-outpost-zeta');
insert into dependency_movie (id,title,"elementID") values (1910, 'Last Starfighter, The','last-starfighter');
insert into dependency_movie (id,title,"elementID") values (1911, 'Leprechaun 4: In Space','leprechaun-4-space');
insert into dependency_movie (id,title,"elementID") values (1913, 'Lifeforce','lifeforce');
insert into dependency_movie (id,title,"elementID") values (1914, 'Lifepod','lifepod');
insert into dependency_movie (id,title,"elementID") values (1915, 'Lockout','lockout');
insert into dependency_movie (id,title,"elementID") values (1916, 'Lost in Space','lost-space');
insert into dependency_movie (id,title,"elementID") values (1917, 'Love','love');
insert into dependency_movie (id,title,"elementID") values (1918, 'Man of Steel','man-steel');
insert into dependency_movie (id,title,"elementID") values (1919, 'Man Who Fell to Earth, The','man-who-fell-earth');
insert into dependency_movie (id,title,"elementID") values (1920, 'Marooned','marooned');
insert into dependency_movie (id,title,"elementID") values (1921, 'Mars Attacks!','mars-attacks');
insert into dependency_movie (id,title,"elementID") values (1922, 'Men in Black','men-black');
insert into dependency_movie (id,title,"elementID") values (1923, 'Men in Black II','men-black-ii');
insert into dependency_movie (id,title,"elementID") values (1924, 'Men in Black 3','men-black-3');
insert into dependency_movie (id,title,"elementID") values (1925, 'Missile to the Moon','missile-moon');
insert into dependency_movie (id,title,"elementID") values (1926, 'Mission Stardust','mission-stardust');
insert into dependency_movie (id,title,"elementID") values (1927, 'Mission to Mars','mission-mars');
insert into dependency_movie (id,title,"elementID") values (1928, 'Moon','moon');
insert into dependency_movie (id,title,"elementID") values (1929, 'Moon Zero Two','moon-zero-two');
insert into dependency_movie (id,title,"elementID") values (1930, 'Moon 44','moon-44');
insert into dependency_movie (id,title,"elementID") values (1931, 'Moonraker','moonraker');
insert into dependency_movie (id,title,"elementID") values (1932, 'Moontrap','moontrap');
insert into dependency_movie (id,title,"elementID") values (1933, 'Muppets from Space','muppets-space');
insert into dependency_movie (id,title,"elementID") values (1934, 'Oblivion','oblivion');
insert into dependency_movie (id,title,"elementID") values (1935, 'October Sky','october-sky');
insert into dependency_movie (id,title,"elementID") values (1936, 'Outland','outland');
insert into dependency_movie (id,title,"elementID") values (1937, 'Outlander','outlander');
insert into dependency_movie (id,title,"elementID") values (1938, 'Pandorum','pandorum');
insert into dependency_movie (id,title,"elementID") values (1939, 'Paradox Alice','paradox-alice');
insert into dependency_movie (id,title,"elementID") values (1940, 'Phantom Planet, The','phantom-planet');
insert into dependency_movie (id,title,"elementID") values (1941, 'Pitch Black','pitch-black');
insert into dependency_movie (id,title,"elementID") values (1942, 'Planet 51','planet-51');
insert into dependency_movie (id,title,"elementID") values (1943, 'Planet Hulk','planet-hulk');
insert into dependency_movie (id,title,"elementID") values (1944, 'Planet of the Vampires','planet-vampires');
insert into dependency_movie (id,title,"elementID") values (1945, 'Precious Find','precious-find');
insert into dependency_movie (id,title,"elementID") values (1946, 'Predator','predator');
insert into dependency_movie (id,title,"elementID") values (1947, 'Predator 2','predator-2');
insert into dependency_movie (id,title,"elementID") values (1948, 'Predators','predators');
insert into dependency_movie (id,title,"elementID") values (1949, 'Project Moonbase','project-moonbase');
insert into dependency_movie (id,title,"elementID") values (1950, 'Proxima','proxima');
insert into dependency_movie (id,title,"elementID") values (1951, 'Queen of Outer Space','queen-outer-space');
insert into dependency_movie (id,title,"elementID") values (1952, 'Race to Space','race-space');
insert into dependency_movie (id,title,"elementID") values (1953, 'Red Planet','red-planet');
insert into dependency_movie (id,title,"elementID") values (1954, 'Riddick','riddick');
insert into dependency_movie (id,title,"elementID") values (1955, 'Right Stuff, The','right-stuff');
insert into dependency_movie (id,title,"elementID") values (1956, 'Robinson Crusoe on Mars','robinson-crusoe-mars');
insert into dependency_movie (id,title,"elementID") values (1957, 'Rocketship X-M','rocketship-x-m');
insert into dependency_movie (id,title,"elementID") values (1958, 'Saturn 3','saturn-3');
insert into dependency_movie (id,title,"elementID") values (1959, 'Scavengers','scavengers');
insert into dependency_movie (id,title,"elementID") values (1960, 'Screamers','screamers');
insert into dependency_movie (id,title,"elementID") values (1961, 'Serenity','serenity');
insert into dependency_movie (id,title,"elementID") values (1962, 'Silent Running','silent-running');
insert into dependency_movie (id,title,"elementID") values (1963, 'Solar Crisis','solar-crisis');
insert into dependency_movie (id,title,"elementID") values (1964, 'Solaris','solaris');
insert into dependency_movie (id,title,"elementID") values (1965, 'Solaris','solaris-0');
insert into dependency_movie (id,title,"elementID") values (1966, 'Soldier','soldier');
insert into dependency_movie (id,title,"elementID") values (1967, 'Spaceballs','spaceballs');
insert into dependency_movie (id,title,"elementID") values (1968, 'Spacecamp','spacecamp');
insert into dependency_movie (id,title,"elementID") values (1969, 'Spacehunter: Adventures in the Forbidden Zone','spacehunter-adventures-forbidden-zone');
insert into dependency_movie (id,title,"elementID") values (1970, 'Spaceways','spaceways');
insert into dependency_movie (id,title,"elementID") values (1971, 'Space Battleship Yamato','space-battleship-yamato');
insert into dependency_movie (id,title,"elementID") values (1972, 'Space Buddies','space-buddies');
insert into dependency_movie (id,title,"elementID") values (1973, 'Space Cowboys','space-cowboys');
insert into dependency_movie (id,title,"elementID") values (1974, 'Space Raiders','space-raiders');
insert into dependency_movie (id,title,"elementID") values (1975, 'Space Station 76','space-station-76');
insert into dependency_movie (id,title,"elementID") values (1976, 'Space Truckers','space-truckers');
insert into dependency_movie (id,title,"elementID") values (1977, 'Space Warriors','space-warriors');
insert into dependency_movie (id,title,"elementID") values (1978, 'Species','species');
insert into dependency_movie (id,title,"elementID") values (1979, 'Starcrash','starcrash');
insert into dependency_movie (id,title,"elementID") values (1980, 'Star Crystal','star-crystal');
insert into dependency_movie (id,title,"elementID") values (1981, 'Starman','starman');
insert into dependency_movie (id,title,"elementID") values (1982, 'Star Quest: The Odyssey','star-quest-odyssey');
insert into dependency_movie (id,title,"elementID") values (1983, 'Star Runners','star-runners');
insert into dependency_movie (id,title,"elementID") values (1984, 'Starship Troopers','starship-troopers');
insert into dependency_movie (id,title,"elementID") values (1985, 'Starship Troopers 2: Hero of the Federation','starship-troopers-2-hero-federation');
insert into dependency_movie (id,title,"elementID") values (1986, 'Starship Troopers 3: Marauder','starship-troopers-3-marauder');
insert into dependency_movie (id,title,"elementID") values (1987, 'Star Trek','star-trek');
insert into dependency_movie (id,title,"elementID") values (1988, 'Star Trek: The Motion Picture','star-trek-motion-picture');
insert into dependency_movie (id,title,"elementID") values (1989, 'Star Trek II: The Wrath of Khan','star-trek-ii-wrath-khan');
insert into dependency_movie (id,title,"elementID") values (1990, 'Star Trek III: The Search for Spock','star-trek-iii-search-spock');
insert into dependency_movie (id,title,"elementID") values (1991, 'Star Trek IV: The Voyage Home','star-trek-iv-voyage-home');
insert into dependency_movie (id,title,"elementID") values (1992, 'Star Trek V: The Final Frontier','star-trek-v-final-frontier');
insert into dependency_movie (id,title,"elementID") values (1993, 'Star Trek VI: The Undiscovered Country','star-trek-vi-undiscovered-country');
insert into dependency_movie (id,title,"elementID") values (1994, 'Star Trek: First Contact','star-trek-first-contact');
insert into dependency_movie (id,title,"elementID") values (1995, 'Star Trek: Generations','star-trek-generations');
insert into dependency_movie (id,title,"elementID") values (1996, 'Star Trek: Insurrection','star-trek-insurrection');
insert into dependency_movie (id,title,"elementID") values (1997, 'Star Trek Into Darkness','star-trek-darkness');
insert into dependency_movie (id,title,"elementID") values (1998, 'Star Trek: Nemesis','star-trek-nemesis');
insert into dependency_movie (id,title,"elementID") values (1999, 'Star Wars Episode I: The Phantom Menace','star-wars-episode-i-phantom-menace');
insert into dependency_movie (id,title,"elementID") values (2000, 'Star Wars Episode II: Attack of the Clones','star-wars-episode-ii-attack-clones');
insert into dependency_movie (id,title,"elementID") values (2001, 'Star Wars: Episode III - Revenge of the Sith','star-wars-episode-iii-revenge-sith');
insert into dependency_movie (id,title,"elementID") values (2002, 'Star Wars: Episode IV - A New Hope','star-wars-episode-iv-new-hope');
insert into dependency_movie (id,title,"elementID") values (2003, 'Star Wars: Episode V - The Empire Strikes Back','star-wars-episode-v-empire-strikes-back');
insert into dependency_movie (id,title,"elementID") values (2004, 'Star Wars: Episode VI - Return of the Jedi','star-wars-episode-vi-return-jedi');
insert into dependency_movie (id,title,"elementID") values (2005, 'Star Wars: Episode VII - The Force Awakens','star-wars-episode-vii-force-awakens');
insert into dependency_movie (id,title,"elementID") values (2006, 'Stargate','stargate');
insert into dependency_movie (id,title,"elementID") values (2007, 'Stranded','stranded');
insert into dependency_movie (id,title,"elementID") values (2008, 'Black Horizon','black-horizon');
insert into dependency_movie (id,title,"elementID") values (2009, 'Sunshine','sunshine');
insert into dependency_movie (id,title,"elementID") values (2010, 'Supernova','supernova');
insert into dependency_movie (id,title,"elementID") values (2011, 'Last Days on Mars, The','last-days-mars');
insert into dependency_movie (id,title,"elementID") values (2012, 'Terrornauts, The','terrornauts');
insert into dependency_movie (id,title,"elementID") values (2013, 'Thing, The','thing');
insert into dependency_movie (id,title,"elementID") values (2014, 'Thing, The','thing-0');
insert into dependency_movie (id,title,"elementID") values (2015, 'This Island Earth','island-earth');
insert into dependency_movie (id,title,"elementID") values (2016, 'Titan A.E.','titan-ae');
insert into dependency_movie (id,title,"elementID") values (2017, 'Total Recall','total-recall');
insert into dependency_movie (id,title,"elementID") values (2018, 'Trapped in Space','trapped-space');
insert into dependency_movie (id,title,"elementID") values (2019, 'Treasure Planet','treasure-planet');
insert into dependency_movie (id,title,"elementID") values (2020, 'A Trip to the Moon','trip-moon');
insert into dependency_movie (id,title,"elementID") values (2021, 'Voyage to the End of the Universe (Ikarie XB 1)','voyage-end-universe-ikarie-xb-1');
insert into dependency_movie (id,title,"elementID") values (2022, 'WALL-E','wall-e');
insert into dependency_movie (id,title,"elementID") values (2023, 'War of the Worlds','war-worlds');
insert into dependency_movie (id,title,"elementID") values (2024, 'War of the Worlds','war-worlds-0');
insert into dependency_movie (id,title,"elementID") values (2025, 'Wild Blue Yonder, The','wild-blue-yonder');
insert into dependency_movie (id,title,"elementID") values (2026, 'Wing Commander','wing-commander');
insert into dependency_movie (id,title,"elementID") values (2027, 'Woman in the Moon','woman-moon');
insert into dependency_movie (id,title,"elementID") values (2028, 'Zenon: Girl of the 21st Century','zenon-girl-21st-century');
insert into dependency_movie (id,title,"elementID") values (2029, 'Zenon: The Zequel','zenon-zequel');
insert into dependency_movie (id,title,"elementID") values (2030, 'Zenon: Z3','zenon-z3');
insert into dependency_movie (id,title,"elementID") values (2031, 'Zathura: A Space Adventure','zathura-space-adventure');
insert into dependency_movie (id,title,"elementID") values (2453, 'Rendezvous in Space. (Complete film from the 1964 World''s Fair)','rendezvous-space-complete-film-1964-worlds-fair-1');
insert into dependency_movie (id,title,"elementID") values (2609, 'Arrival','arrival');