# Generated by Django 2.0.1 on 2018-01-29 04:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dependency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predecessors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=2)),
                ('document', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Successors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=2)),
                ('document', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='edge',
            name='from_task',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='to_task',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='dependencies',
        ),
        migrations.AddField(
            model_name='tasks',
            name='TRL',
            field=models.SmallIntegerField(choices=[(1, '1. Basic principles observed and reported'), (2, 'Technology concept and/or application formulated'), (3, 'Analytical and experimental critical function and/or characteristic proof of concept'), (4, 'Component and/or breadboard validation in laboratory environment '), (5, 'Component and/or breadboard validation in relevant environment'), (6, 'System/subsystem model or prototype demonstration in a relevant environment (ground or space)'), (7, 'System prototype demonstration in a space environment'), (8, 'Actual system completed and "flight qualified" through test and demonstration (ground or space)'), (9, 'Actual system "flight proven" through successful mission operations')], null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='confidence',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
        migrations.DeleteModel(
            name='Edge',
        ),
        migrations.AddField(
            model_name='successors',
            name='successor_source_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='successor_source_task', to='dependency.Tasks'),
        ),
        migrations.AddField(
            model_name='successors',
            name='successor_target_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='successor_target_to_task', to='dependency.Tasks'),
        ),
        migrations.AddField(
            model_name='predecessors',
            name='predecessor_source_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='predecessor_source_task', to='dependency.Tasks'),
        ),
        migrations.AddField(
            model_name='predecessors',
            name='predecessor_target_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='predecessor_target_task', to='dependency.Tasks'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='predecessor',
            field=models.ManyToManyField(blank=True, related_name='predecessors', through='dependency.Predecessors', to='dependency.Tasks'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='successor',
            field=models.ManyToManyField(blank=True, related_name='successors', through='dependency.Successors', to='dependency.Tasks'),
        ),
    ]
