# Generated by Django 2.0.1 on 2018-03-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependency', '0003_auto_20180211_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='elementID',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='legacyUrl',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
