# Generated by Django 2.0.3 on 2018-08-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependency', '0005_auto_20180812_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='elementID',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='librarything_id',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='elementID',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='tmdb_id',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
