# Generated by Django 2.0.3 on 2018-09-08 20:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dependency', '0009_auto_20180907_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author2',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
