# Generated by Django 2.0.3 on 2018-09-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependency', '0010_auto_20180908_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='year',
        ),
        migrations.AddField(
            model_name='book',
            name='release_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
