# Generated by Django 2.0.3 on 2018-09-08 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dependency', '0011_auto_20180908_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='release_Date',
            new_name='release_date',
        ),
    ]
