# Generated by Django 2.0.3 on 2018-09-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependency', '0012_auto_20180908_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='elementID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
